from selenium import webdriver
import time
driver=webdriver.Chrome()
driver.get("https://www.gmail.com/")
driver.implicitly_wait(10)
driver.find_element_by_xpath("//*[@autocomplete='username' and @class='whsOnd zHQkBf']").send_keys("santoshn.shankar@gmail.com")
driver.find_element_by_xpath("//*[@class='RveJvd snByac']").click()
driver.find_element_by_xpath("//*[@jsname='YPqjbf' and @name='password']").send_keys("appaammasati")
driver.find_element_by_xpath("//*[@class='RveJvd snByac']").click()
# driver.find_element_by_xpath("//*[@gh='cm' and @style='user-select: none;']").click()
# driver.maximize_window()
# driver.find_element_by_xpath("//*[@class='aoD hl' and @tabindex='1']").click()
# driver.find_element_by_xpath("//*[@class='vO' and @aria-label='To' and @rows='1' and @autocorrect='off']").send_keys("santhu.ns.in@gmail.com")
# driver.find_element_by_xpath("//*[@name='subjectbox' and @aria-label='Subject']").send_keys("1 4 3")
# driver.find_element_by_xpath("//*[@hidefocus='true' and @aria-label='Message Body']").send_keys("My first automated mail!!?")
# driver.find_element_by_xpath("//*[@role='button' and @data-tooltip='Send ‪(Ctrl-Enter)‬']").click()
time.sleep(5)
driver.find_element_by_xpath("//div[@class='aio UKr6le']/span/a[@title='Sent']").click()
sentmail=driver.find_element_by_xpath("//*[@class='BltHke nH oy8Mbf']/div[3]/div/div/table/tbody/tr[1]")
sentmail.click()
print(sentmail.text)
subject_line=driver.find_element_by_xpath("//h2[text()='1 4 3']").text
print("--------------")
print(subject_line)
if subject_line == "1 4 3":
    print("i am deleting the message i have sent you")
    time.sleep(5)
    driver.find_element_by_xpath("//*[@aria-label='Delete']").click()